services:
  bot:
    image: 192.168.0.168:5000/discord-util-bot-v3:latest
    pull_policy: always
    restart: unless-stopped
    env_file: .env
    volumes:
      - /backups/discord-util-bot-v3:/app/backups
